version: '3'

services:

  mongo:
    container_name: "mongo-triage"
    image: "mongo:latest"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_MANAGEMENT_DATABASE=${MONGO_INITDB_MANAGEMENT_DATABASE}
      - MONGO_INITDB_MANAGEMENT_COLLECTION=${MONGO_INITDB_MANAGEMENT_COLLECTION}
      - MONGO_INITDB_QUEUE_DATABASE=${MONGO_INITDB_QUEUE_DATABASE}
      - MONGO_INITDB_PENDING_TRIAGES_COLLECTION=${MONGO_INITDB_PENDING_TRIAGES_COLLECTION}
      - MONGO_INITDB_USERNAME=${MONGO_INITDB_USERNAME}
      - MONGO_INITDB_PASSWORD=${MONGO_INITDB_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./:/docker-entrypoint-initdb.d
      - mongo-triage:/data/db

  mongo-express:
    container_name: "mongo-express-triage"
    image: "mongo-express"
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

  rabbit-mq:
    container_name: "rabbit-mq-notifications"
    build:
      context: .
      dockerfile: rabbitmq-dockerfile
    restart: always
    ports:
      - 5672:5672
      - 61613:61613
      - 8082:15672

volumes:
  mongo-triage:
